os: linux
language: node_js
node_js: 12
# branches:
#     only:
#         - master
install:
    - yarn
script:
    - npm run lint
    - npm run build
deploy:
    provider: script
    skip_cleanup: true
    on:
        branch: master
    script:
        - npm run release
cache:
    directories:
        - node_modules
